name: cskitchen
description: Order your favourite Cs kitchen takeaway food and get it delivered to your door step.

version: 1.0.0+24

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  firebase_auth: 1.0.0
  cloud_firestore: 1.0.0
  shared_preferences: 2.0.3
  http: 0.13.0
  webview_flutter: 2.0.1
  cached_network_image: 3.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/cs_icon1.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/cs_icon1.png"

flutter:
  uses-material-design: true

  assets:
    #- assets/cs_icon1.png
    - assets/cs_icon.png
    - assets/backgroundTwo.jpg
    - assets/logo.png

  fonts:
    - family: kalam Regular
      fonts:
        - asset: fonts/Kalam-Regular.ttf
