name: cskitchen
description: A restaurant management app.

version: 0.0.1+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  shared_preferences: ^0.5.12+4
  http: ^0.12.0+4
  webview_flutter: ^0.3.18+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  image_path: "assets/cs_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/cs_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/chips.jpg
    - assets/cs_icon.png
    - assets/cs_logo.png

  fonts:
    - family: Indie
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
    - family: Cookie
      fonts:
        - asset: fonts/Cookie-Regular.ttf
    - family: Caveat Regular
      fonts:
        - asset: fonts/Caveat-Regular.ttf
    - family: Caveat Bold
      fonts:
        - asset: fonts/Caveat-Bold.ttf
    - family: Great Vibes
      fonts:
        - asset: fonts/GreatVibes-Regular.ttf
    - family: kalam Regular
      fonts:
        - asset: fonts/Kalam-Regular.ttf
