name: cskitchen
description: cskitchen food ordering app.

version: 0.0.1+11

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  shared_preferences: ^2.0.3
  http: ^0.13.0
  webview_flutter: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/cs_icon1.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/cs_icon1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/chips.jpg
    - assets/cs_icon.png
    - assets/cs_icon1.png
    - assets/cs_logo.png

  fonts:
    - family: Indie
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
    - family: Cookie
      fonts:
        - asset: fonts/Cookie-Regular.ttf
    - family: Caveat Regular
      fonts:
        - asset: fonts/Caveat-Regular.ttf
    - family: Caveat Bold
      fonts:
        - asset: fonts/Caveat-Bold.ttf
    - family: Great Vibes
      fonts:
        - asset: fonts/GreatVibes-Regular.ttf
    - family: kalam Regular
      fonts:
        - asset: fonts/Kalam-Regular.ttf
